default: &default
  adapter: postgresql
  host: localhost
  username: eziz
  password: eziz2010@
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: rails_dev

test:
  <<: *default
  database: rails_test

production:
  <<: *default
  database: awaza_prod
  url: <%= ENV['DATABASE_URL'] %>

